name: Compiler checks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check Python syntax
        run: make compile
      - name: Run local tests
        run: make test
